version: 1
disable_existing_loggers: true
formatters:
  ty:
    class: elogger.TyphoonFormatter
    datefmt: |-
      %Y-%m-%dT%H:%M:%S%z
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
    formatter: ty
loggers:
  "":
    handlers:
    - console
    level: DEBUG
    propogate: yes
  uvicorn:
    level: WARN
