apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: admin@oz.net.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - selector: {}
        http01:
          ingress: {}
          #  class: nginx
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-prod

