apiVersion: v1
kind: ConfigMap
metadata:
  name: http-inspect-cfg
  namespace: default
data:
  logging: |
    version: 1
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        stream: ext://sys.stdout
    root:
      handlers:
      - console

