apiVersion: v1
kind: Secret
metadata:
  name: elastic-user
  namespace: cattle-logging-system
type: Opaque
data:
  accessKey: ZWxhc3RpYw==
  elastic: eW9oZjFWb2g=
  secretKey: eW9oZjFWb2g=
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: es
  namespace: cattle-logging-system
spec:
  elasticsearch:
    default_elasticsearch_version: "7"
    # host: stage.ty.oz.net.ru
    host: 78.46.81.238
    port: 9200
    scheme: http
    user: elastic
    password:
      valueFrom:
        secretKeyRef:
          name: elastic-user
          key: elastic
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: all-logs
  namespace: cattle-logging-system
spec:
  globalOutputRefs:
  - es

