apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: environment
  namespace: default
spec:
  selector:
    matchLabels:
      app: http-inspect
  env:
    - name: __ENVIRONMENT
      value: stage

