apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
# provisioner: kubernetes.io/no-provisioner
provisioner: rancher.io/local-path
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

